[DOC] Ajout de talks
1024pix/pix-lifestyle pull request #10
Opened 2022-06-08 16:34 UTC by octo-topi

Il en manquait !
J'ai renommé en retour d'expérience pour être un peu plus large

2022-06-09 08:20 UTC, Radioreve requested changes

2022-06-09 08:20 UTC, Radioreve commented on README.md
> +    * [On partage nos expériences](autre/partage.md)
Pourquoi avoir remplacé et pas simplement ajouté ?

2022-06-09 08:35 UTC, octo-topi commented on README.md
> +    * [On partage nos expériences](autre/partage.md)
Ca se discute. J'ai rassemblé des liens, je me suis rendu compte qu'il n'y avait pas que des talks, j'ai cherché un nom.
Mais je peux garder `conferences` et créer `podcast` en plus

2022-06-09 14:36 UTC, Radioreve commented on README.md
> +    * [On partage nos expériences](autre/partage.md)
Je préfère oui.

2022-06-29 13:32 UTC, VincentHardouin approved these changes

2022-06-29 18:25 UTC, aceol commented on autre/partage.md
> +* Blog - [Le blog Pix](https://engineering.pix.fr/)
Je me permet de rajouter ca, vu que c'est un retour d'experience sur la gestion git chez Pix
Les emojis c'est en option aussi ;)

```suggestion
* 📝 Blog - [Le blog Pix](https://engineering.pix.fr/)
* 📣 Talk - Devoxx 2022 - Antoine [Git, back to the future](https://www.youtube.com/watch?v=QCsFFAc5ffc)
```

2022-06-29 18:25 UTC, aceol approved these changes

2022-08-04 12:13 UTC, MelanieMEB commented on README.md
> +    * [On partage nos expériences](autre/partage.md)
J'ai fait un commit pour mettre tout, parce qu'entre les talk, les table ronde, les podcast, etc... c'est assez large !

2022-08-18 09:58 UTC, merged